dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
  - mkdir -p build
  - cd build
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake -j2 -D ENABLE_COVERAGE:BOOL=TRUE ..
  - make all
  - ctest -j2
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-7
