dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

script:
  - mkdir -p build
  - cd build
  - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 cmake ..
  - make all
  - ctest
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-5
