dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make all
  - ctest
